[package]
name = "craftcad_io_dxf"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
craftcad_errors = { path = "../errors" }
craftcad_io = { path = "../io" }
