[package]
name = "diycad_common"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
directories = "5"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror.workspace = true
