[package]
name = "craftcad_diag"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
zip = "0.6"
base64 = "0.22"
