[package]
name = "craftcad_commands"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
craftcad_serialize = { path = "../serialize" }
serde_json = "1"
uuid = { version = "1", features = ["v4"] }

[dev-dependencies]
serde_json = "1"
