[package]
name = "craftcad_sketch"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
craftcad_geom2d = { path = "../geom2d" }
craftcad_errors = { path = "../errors", package = "craftcad_errors" }
serde = { version = "1", features = ["derive"] }
